from enum import Enum

class ResourceType(Enum):

    DEVICE = 'device'
    BRIDGE_HOME = 'bridge_home'
    ROOM = 'room'
    ZONE = 'zone'
    SERVICE_GROUP = 'service_group'
    LIGHT = 'light'
    BUTTON = 'button'
    RELATIVE_ROTARY = 'relative_rotary'
    TEMPERATURE = 'temperature'
    LIGHT_LEVEL = 'light_level'
    MOTION = 'motion'
    CAMERA_MOTION = 'camera_motion'
    ENTERTAINMENT = 'entertainment'
    CONTACT = 'contact'
    TAMPER = 'tamper'
    GROUPED_LIGHT = 'grouped_light'
    GROUPED_MOTION = 'grouped_motion'
    GROUPED_LIGHT_LEVEL = 'grouped_light_level'
    DEVICE_POWER = 'device_power'
    DEVICE_SOFTWARE_UPDATE = 'device_software_update'
    ZIGBEE_BRIDGE_CONNECTIVITY = 'zigbee_bridge_connectivity'
    ZIGBEE_CONNECTIVITY = 'zigbee_connectivity'
    ZGP_CONNECTIVITY = 'zgp_connectivity'
    REMOTE_ACCESS = 'remote_access'
    BRIDGE = 'bridge'
    ZIGBEE_DEVICE_DISCOVERY = 'zigbee_device_discovery'
    SYSTEM_UPDATE = 'system_update'
    HOMEKIT = 'homekit'
    MATTER = 'matter'
    MATTER_FABRIC = 'matter_fabric'
    SCENE = 'scene'
    ENTERTAINMENT_CONFIGURATION = 'entertainment_configuration'
    PUBLIC_IMAGE = 'public_image'
    AUTH_V1 = 'auth_v1'
    BEHAVIOR_SCRIPT = 'behavior_script'
    BEHAVIOR_INSTANCE = 'behavior_instance'
    GEOFENCE = 'geofence'
    GEOFENCE_CLIENT = 'geofence_client'
    GEOLOCATION = 'geolocation'
    SMART_SCENE = 'smart_scene'
